# Generated by Django 3.1.4 on 2021-07-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos_realizados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='trabajos'),
        ),
    ]
